---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployment
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - uccps.uccps.document.domain
  resources:
  - documents
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - uccps.uccps.document.domain
  resources:
  - documents/finalizers
  verbs:
  - update
- apiGroups:
  - uccps.uccps.document.domain
  resources:
  - documents/status
  verbs:
  - get
  - patch
  - update
